global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:3000

  - job_name: worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - worker:9101

  - job_name: publisher
    metrics_path: /metrics
    static_configs:
      - targets:
          - publisher:9102

  - job_name: scheduler
    metrics_path: /metrics
    static_configs:
      - targets:
          - scheduler:9103
